
create_meshes:
	mkdir -p meshes
	python refine_mesh.py 4

taylortest:
	mkdir -p meshes
	python3 plot_taylor.py


equilateral:
	mkdir -p meshes
	python3 refine_mesh.py 7
	python3 equilateral.py

five_cables:
	mkdir -p meshes
	python3 refine_mesh.py 7
	python3 five_cables.py

timings:
	mkdir -p meshes
	python3 refine_mesh.py 7
	python3 timings.py
